namespace Dm
{
	internal class SQLStateMapping
	{
		private int m_Err;

		private string m_SQLState;

		private string m_ErrInfo;

		public static SQLStateMapping[] mappings = new SQLStateMapping[162]
		{
			new SQLStateMapping(DmErrorDefinition.EC_EMPTY, "02000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_SUCCESS, "00000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_PARSE_ERROR, "42000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_COMMENT_IN_PREPARE, "30000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_STMT_TYPE_MISMATCH, "42000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_NOT_SUPPORTED, "30000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_PARSE_ERROR_EXPLAIN, "42000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_RECV_OOB, "08000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_DB_NAME, "3D000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_SAME_DB_NAME, "3D000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_ROLE_NAME, "0P000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_SCHEMA_NAME, "3F000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_SAVEPOINT_NAME, "3B000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_CURSOR_NAME, "34000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_DB_OBJECT, "3D000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_SYSROLE_NAME, "0P000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_READONLY_TRANS, "25006", ""),
			new SQLStateMapping(DmErrorDefinition.EC_SUSPEND_TRANS, "25000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_UNAUTHORIZED_USER, "28000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_OLD_ROW_REF_ASSGIN_VALUE, "27000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_CHG_NEW_ROW_REF_IN_WRONG_TRG, "27000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_TRIGGER_ACTION, "09000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_EXPRESSION, "2201B", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DATA_LOSE_WARN, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DATA_CNV_FAIL, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DATA_OVERFLOW, "22000", DmConst.res.GetString("error.EC_DATA_OVERFLOW", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_DATA_DIV_ZERO, "22012", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DATA_ILLEGAL_CHAR, "22021", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DATATYPE_NOT_MATCH, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_ESC_CHAR, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_ESC_SEQ, "22019", ""),
			new SQLStateMapping(DmErrorDefinition.EC_STR_TRUNC, "22001", ""),
			new SQLStateMapping(DmErrorDefinition.EC_STR_CAST, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DATETIME_OVERFLOW, "22008", DmConst.res.GetString("error.EC_DATETIME_OVERFLOW", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_CAST_LOST_IMFO, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_CAST_LOST_PREC, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_INTERVAL, "22007", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INTERVAL_OVERFLOW, "22015", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_DATETIME, "22007", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_DATA_TYPE, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_PREC_OUT_OF_LENGTH, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_DEC_OUT_OF_LENGTH, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_INVALID_DATE, "22007", ""),
			new SQLStateMapping(DmErrorDefinition.EC_STR_TOO_LONG, "22000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_RN_SET_TRANS, "25000", ""),
			new SQLStateMapping(DmErrorDefinition.EC_RN_INVALID_SAVEPNT_NAME, "3B001", DmConst.res.GetString("error.EC_RN_INVALID_SAVEPNT_NAME", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_RN_INVALID_DATA, "22000", DmConst.res.GetString("error.EC_RN_INVALID_DATA", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_RN_INVALID_CURSOR_STATE, "24000", DmConst.res.GetString("error.EC_RN_INVALID_CURSOR_STATE", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_RN_INVALID_DB_NAME, "3D000", DmConst.res.GetString("error.EC_RN_INVALID_DB_NAME", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_RN_INVALID_SCHEMA_NAME, "3F000", DmConst.res.GetString("error.EC_RN_INVALID_SCHEMA_NAME", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_RN_NO_ACC_PRIVILEGE, "42000", DmConst.res.GetString("error.EC_RN_NO_ACC_PRIVILEGE", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_CONNECT_LOST, "08000", DmConst.res.GetString("error.EC_CONNECT_LOST", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_EXCEDD_MAX_SESSION_LIMIT, "08000", DmConst.res.GetString("error.EC_EXCEDD_MAX_SESSION_LIMIT", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_EXCEED_MAX_SESSION_PER_USER, "08000", DmConst.res.GetString("error.EC_EXCEED_MAX_SESSION_PER_USER", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_CONNECT_CAN_NOT_ESTABLISHED, "08004", DmConst.res.GetString("error.EC_CONNECT_CAN_NOT_ESTABLISHED", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_COMMUNITION_ERROR, "08S01", DmConst.res.GetString("error.cumunationError", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_MSG_CHECK_ERROR, "HY021", DmConst.res.GetString("error.msgCheckError", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_SQL_IS_EMPTY, "40003", DmConst.res.GetString("error.sqlIsNullOrEmpty", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_OVER_FLOW, "22003", DmConst.res.GetString("error.overflow", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_TIME_INTERVAL, "22007", DmConst.res.GetString("error.invalidTimeIntervalValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_UNSUPPORTED_TYPE, "HY004", DmConst.res.GetString("error.unsupportedType", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DATA_CONVERTION_ERROR, "HY096", DmConst.res.GetString("error.dataConvertionError", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_READ_ONLY_CONNECTION, "01001", DmConst.res.GetString("error.readOnlyConnection", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SQL_TYPE, "HY004", DmConst.res.GetString("error.invalidSqlType", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SEQUENCE, "HY093", DmConst.res.GetString("error.invalidSequence", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_DB_NAME, "3D000", DmConst.res.GetString("error.invalidDbName", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_DIGITAL_FORMAT, "22003", DmConst.res.GetString("error.invalidDigitalTypeFormat", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_DATA_FORMAT, "22007", DmConst.res.GetString("error.invalidDateTypeFormat", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_TIME_FORMAT, "22007", DmConst.res.GetString("error.invalidTimeTypeFormat", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_DATETIME_FORMAT, "22007", DmConst.res.GetString("error.invalidDateTimeTypeFormat", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_COLUMN_TYPE, "HY004", DmConst.res.GetString("error.invalidColumnType", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_COLUMN_NAME, "HY111", DmConst.res.GetString("error.invalidColumnName", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_BIGDIGITAL_FORMAT, "22003", DmConst.res.GetString("error.invalidBigDecimalTypeFormat", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_RESULTSET_TYPE, "01001", DmConst.res.GetString("error.invalidResultsetType", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALUID_ROW_NUMBER, "HY107", DmConst.res.GetString("error.invalidRowNo", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_EMPTY_RESULTSET, "HY020", DmConst.res.GetString("error.emptyResultset", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_CURSOR_MOVE_DIRECTION, "HYC00", DmConst.res.GetString("error.invalidCursorMoveDirection", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_FORWORD_ONLY_RESULTSET, "HY024", DmConst.res.GetString("error.forwardOnlyResultset", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NOT_ALLOW_NULL, "HY024", DmConst.res.GetString("error.notAllowNull", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_CATALOG, "3D000", DmConst.res.GetString("error.invalidDbName", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_RESULTSET_NOT_IN_INSERT_STATUS, "01001", DmConst.res.GetString("error.resultsetNotInInsertStatus", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_RESULTSET_IS_READ_ONLY, "42000", DmConst.res.GetString("error.resultsetInReadOnlyStatus", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_UNSUPPORED_INTERFACE, "HYC00", DmConst.res.GetString("error.unsupportedInterfase", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SEQUENCE_NUMBER, "42S22", DmConst.res.GetString("error.invalidSequenceNo", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_RETURN_VALUE, "HY024", DmConst.res.GetString("error.invalidReturnValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_RESULTSET_CLOSED, "08007", DmConst.res.GetString("error.resultsetClosed", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_STATEMENT_HANDLE_CLOSED, "08007", DmConst.res.GetString("error.statementHandleClosed", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_PARAMETER_VALUE, "HY024", DmConst.res.GetString("error.invalidParameterValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_TRAN_ISOLATION, "HYC00", DmConst.res.GetString("error.invalidTranIsolation", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_SAVEPOINT_IN_AUTOCOMMIT_MODE, "HY012", DmConst.res.GetString("error.savepointInAutoCommitMode", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_ROLLBACK_TO_SAVEPOINT_IN_AUTOCOMMIT_MODE, "HY012", DmConst.res.GetString("error.rollbackToSavepointInAutoCommitMode", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_RELEASE_SAVEPOINT_IN_AUTOCOMMIT_MODE, "HY012", DmConst.res.GetString("error.releaseSavepointInAutoCommitMode", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_COMMIT_IN_AUTOCOMMIT_MODE, "HY012", DmConst.res.GetString("error.commitInAutoCommitMode", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_ROLLBACK_IN_AUTOCOMMIT_MODE, "HY012", DmConst.res.GetString("error.rollbackInAutoCommitMode", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_INPUT_PARAMETER_VALUE, "21S01", DmConst.res.GetString("error.invalidInputParameterValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_OUTPUT_PARAMETER_VALUE, "21S01", DmConst.res.GetString("error.invalidOutParameterValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CANNOT_GET_SAVEPOINT_ID, "42000", DmConst.res.GetString("error.canNotGetSavepointID", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CANNOT_GET_SAVEPOINT_NAME, "42000", DmConst.res.GetString("error.canNotGetSavepointName", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_UNKNOWN_PARAMETER_TYPE, "22002", DmConst.res.GetString("error.unknownParameterType", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SCALE, "HY104", DmConst.res.GetString("error.invalidScale", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_PARAMETER_NAME, "HY093", DmConst.res.GetString("error.invalidParameterName", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SAVEPOINT_NAME, "HY092", DmConst.res.GetString("error.invalidSavepointName", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_PARAMETER_PREC_TOO_BIG, "HY104", DmConst.res.GetString("error.tooBigParameterPrecsicion", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_SAVEPOINT_RELEASED, "HY009", DmConst.res.GetString("error.savepointReleased", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_UNBINDED_PARAMETER, "21S01", DmConst.res.GetString("error.unbindedParameter", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_CURSOR_VALUE, "HY024", DmConst.res.GetString("error.invalidCursorValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_LENGTH_OR_OFFSET, "22025", DmConst.res.GetString("error.invalidLenOrOffset", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CONNECTION_CLOSED, "08003", DmConst.res.GetString("error.connectionClosedOrNotBuild", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NEGOTIATE_FAIL, "08003", DmConst.res.GetString("error.encrypt.negotiate.fail", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_KERBEROS_FAIL, "08003", DmConst.res.GetString("error.init.kerberos.fail", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_GET_FQDN_FAIL, "08003", DmConst.res.GetString("error.getFQDN.fail", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_LOB_LENGTH_ERROR, "", DmConst.res.GetString("error.Lob.length", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_COMMAND_TYPE, "", DmConst.res.GetString("error.commandTypeError", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_CONNECT_PROPERTY, "", DmConst.res.GetString("error.connection.invalidProperty", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SCHEMA_RESTRICTIONS, "", DmConst.res.GetString("error.invalidSchemaRestriction", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_INDEXCOL_RESTRICTIONS, "", DmConst.res.GetString("error.invalidIndexColRestriction", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CONNCTION_NOT_OPENED, "", DmConst.res.GetString("error.connectionClosedOrNotBuild", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_TRX_NOLONGER_USABLE, "", DmConst.res.GetString("error.Trx.NotUsable", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_OPT_FAIL, "", DmConst.res.GetString("error.optError", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_SVR_VERSION_WRONG, "", DmConst.res.GetString("error.version", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NULL_VALUE, "", DmConst.res.GetString("error.nullValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_MUL_REFCURSOR, "", DmConst.res.GetString("error.mulRefCursor", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NOT_FUNCTION, "", DmConst.res.GetString("error.notFunction", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_ENUM_VALUE, "", DmConst.res.GetString("error.invalidNumValue", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_READ_NO_DATA, "", DmConst.res.GetString("error.readnodata", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_COL_NUMBER, "", DmConst.res.GetString("error.invalidcolnumber", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NAME_TOO_LONG, "", DmConst.res.GetString("error.nametoolong", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_COMMAND_TIME_OUT, "", DmConst.res.GetString("error.commandtimeout", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NO_COMMAND_TEXT, "", DmConst.res.GetString("error.commandnotext", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DATAREADER_ALREADY_OPENED, "", DmConst.res.GetString("error.datareaderAlreadyOpened", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CONNECTION_SWITCHED, "", DmConst.res.GetString("error.switched", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CONNECTION_SWITCH_FAILED, "", DmConst.res.GetString("error.switchfailed", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_STR_CUT, "", DmConst.res.GetString("error.stringCut", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_PARAM_IO_TYPE_MISMATCH, "", DmConst.res.GetString("error.EC_PARAM_IO_TYPE_MISMATCH", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_ONLY_DMPARAMETER, "", DmConst.res.GetString("error.ECNET_ONLY_DMPARAMETER", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_SEQUENTIALACCESS_ERROR, "", DmConst.res.GetString("error.ECNET_SEQUENTIALACCESS_ERROR", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_DAY, "", DmConst.res.GetString("error.invalid_day", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_MONTH, "", DmConst.res.GetString("error.invalid_month", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_YEAR, "", DmConst.res.GetString("error.invalid_year", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_HOUR12, "", DmConst.res.GetString("error.invalid_hour12", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_HOUR24, "", DmConst.res.GetString("error.invalid_hour24", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_MINUTE, "", DmConst.res.GetString("error.invalid_minute", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SECOND, "", DmConst.res.GetString("error.invalid_second", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_MILLSECOND, "", DmConst.res.GetString("error.invalid_millsecond", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_AM, "", DmConst.res.GetString("error.invalid_am", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_TZH, "", DmConst.res.GetString("error.invalid_tzh", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_TZM, "", DmConst.res.GetString("error.invalid_tzm", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_TZ, "", DmConst.res.GetString("error.invalid_tz", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DATEFORMAT_NOT_DIGIT_CHAR, "", DmConst.res.GetString("error.dateformat_not_digit_char", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DATEFORMAT_STR_NOT_MATCH, "", DmConst.res.GetString("error.dateformat_str_not_match", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DATEFORMAT_STR_TOO_SHORT, "", DmConst.res.GetString("error.dateformat_str_too_short", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.EC_MSG_LEN_TOO_LONG, "", DmConst.res.GetString("error.msg_len_too_long", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_PARAMETER_DmDbTYPE, "", DmConst.res.GetString("error.invalid_Parameter_DmDbType", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_COMPLEX_TYPE_NAME, "", DmConst.res.GetString("error.invalid_complex_type_name", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_INVALID_SERVER_MODE, "", DmConst.res.GetString("error.invalid_server_mode", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DATA_TOO_LONG, "", DmConst.res.GetString("error.data_too_long", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_MSG_LEN_TOO_LONG, "", DmConst.res.GetString("error.msg_len_too_long", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_NOT_SUPPORT_ENCRYPT, "", DmConst.res.GetString("error.not_support_encrypt", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_ENCRYPT_FAIL, "", DmConst.res.GetString("error.encrypt_fail", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DECRYPT_FAIL, "", DmConst.res.GetString("error.decrypt_fail", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_DIGEST_FAIL, "", DmConst.res.GetString("error.digest_fail", DmConst.ci)),
			new SQLStateMapping(DmErrorDefinition.ECNET_CHECK_DIGEST_FAIL, "", DmConst.res.GetString("error.check_digest_fail", DmConst.ci))
		};

		public int GetErr => m_Err;

		public string GetSQLState => m_SQLState;

		public string GetErrInfo => m_ErrInfo;

		internal SQLStateMapping(int i, string state, string info)
		{
			m_Err = i;
			m_SQLState = state;
			m_ErrInfo = info;
		}
	}
}
